[package]
name = "rust_collector"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"    
udev = "0.8"       
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"  
procfs = "0.15"     
notify = "6.1"      
