name: R-ETF Agent CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python 3.9 and install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install requests

      - name: Set up Node.js 20 and install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --prefix ./node_ui

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust and Java components
        run: |
          cargo build --release --manifest-path=rust_collector/Cargo.toml
          javac java_manager/AgentManager.java

      - name: Assemble Release Package
        run: |
          mkdir release
          cp rust_collector/target/release/rust_collector release/
          cp -r java_manager release/
          cp -r python_orchestrator release/
          cp -r node_ui release/
          cp test_harness.sh release/
          rm -f release/java_manager/AgentManager.java

      - name: Upload Agent Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: retf-agent-linux-build
          path: release/

  integration-test:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev netcat-openbsd curl

      - name: Set up all language runtimes
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install requests
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --prefix ./node_ui
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build all components for test
        run: |
          cargo build --release --manifest-path=rust_collector/Cargo.toml
          javac java_manager/AgentManager.java

      - name: Correct file paths in agent config
        run: |
          WORKING_DIR=$(pwd)
          sed -i "s|/home/RETF_Agent|$WORKING_DIR|g" java_manager/agent.properties

      - name: Start Node UI in background
        run: |
          nohup npm start --prefix ./node_ui > node_ui.log 2>&1 &
          sleep 10
          echo "✅ Node UI started, checking health..."
          curl -f http://localhost:4000 || (echo "❌ Node UI not responding!" && cat node_ui.log && exit 1)

      - name: Run agent and automated test
        run: |
          sudo java -cp java_manager AgentManager &> agent_output.log &
          sleep 15

          sudo bash test_harness.sh
          sleep 15

          echo "--- AGENT LOGS ---"
          cat agent_output.log
          echo "--------------------"

      - name: Verify alerts were triggered
        run: |
          grep "Connection to IP Address on Web Port" agent_output.log
          grep "Potential Ransomware Note" agent_output.log
          echo "SUCCESS: All expected alerts were found in the log file."
