name: R-ETF Agent CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - uses: actions/setup-java@v4
        with: { java-version: '11', distribution: 'temurin' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.9' }
      - run: pip install requests
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install --prefix ./node_ui
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable, override: true }
      - name: Build all components
        run: |
          cargo build --release --manifest-path=rust_collector/Cargo.toml
          javac java_manager/AgentManager.java
      - name: Assemble and Upload Artifact
        run: |
          mkdir release
          cp rust_collector/target/release/rust_collector release/
          cp -r java_manager release/
          cp -r python_orchestrator release/
          cp -r node_ui release/
          cp test_harness.sh release/
          rm -f release/java_manager/AgentManager.java
      - uses: actions/upload-artifact@v4
        with:
          name: retf-agent-linux-build
          path: release/

  integration-test:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev netcat
      - uses: actions/setup-java@v4
        with: { java-version: '11', distribution: 'temurin' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.9' }
      - run: pip install requests
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm install --prefix ./node_ui
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable, override: true }
      - name: Build all components
        run: |
          cargo build --release --manifest-path=rust_collector/Cargo.toml
          javac java_manager/AgentManager.java
      - name: Run agent and automated test
        run: |
          # Start agent in background, logging to a file
          sudo java -cp java_manager AgentManager &> agent_output.log &
          sleep 15 # Wait for agent to fully initialize

          # Run the test harness with sudo privileges
          sudo bash ./test_harness.sh
          sleep 15 # Wait for alerts to be processed

          echo "--- AGENT LOGS ---"
          cat agent_output.log
          echo "--------------------"

      - name: Verify alerts were triggered
        run: |
          # This now checks for the alerts that are GUARANTEED to be generated
          grep "System Information Discovery" agent_output.log
          grep "Script Execution from /tmp" agent_output.log
          grep "Suspicious Process Execution: Netcat" agent_output.log
          grep "Password File Modification" agent_output.log
          echo "✅ SUCCESS: All expected alerts were found in the log file."
